name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["plugins/**/*", "tests/**/*"]

  push:
    branches:
    - main
    paths:
    - "plugins/**/*"

jobs:

  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python env
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: upgrade pip
        run:
          python -m pip install --upgrade pip

      - name: install pytest
        run:
          pip install pytest

      - name: run core tests
        run: pytest -s -v tests
